const getPageDeclarationTemplate = (componentConfig) => ` 
<script>
var activity = {
  page: {
    components: [
        ${componentConfig},
      {
        detail: {
          name: "vue-button",
        },
        mark: "vue-button-1710828895681",
        style: {},
        baseEvent: [
          {
            conditionConfig: { isOpen: false, relation: "and" },
            event: "none",
            failEvent: "none",
            moreSetting: true,
            isSeedCRM: false,
            sourceType: "",
            backWash: { isOpen: false, isJumpToHome: false, url: "" },
            isKeyBehavior: false,
            isRecord: false,
            historyEvent: [],
            historyFailEvent: [],
          },
        ],
        statInfo: { button: "按钮" },
        clientRects: {
          x: 791.5,
          y: 290,
          width: 306,
          height: 42.796875,
          top: 290,
          right: 1097.5,
          bottom: 332.796875,
          left: 791.5,
        },
      },
    ],
    detail: {
      canvasMode: "auto",
      deviceType: "Mobile",
      canvasMinWidth: "",
      desktopCanvasWidth: "",
      desktopCanvasHeight: "",
      clientWindowWidth: "",
      clientWindowHeight: "",
      isClientWindowMax: true,
      name: "devtest-random-01",
      date: ["2024-03-18T16:00:00.000Z", "3024-03-19T15:59:59.000Z"],
      title: "页面名称",
      description: "",
      protocol: [],
      hasComment: false,
      authentication: false,
      onShowReload: false,
      isShare: true,
      shareType: "default",
      shareTitle: "",
      shareContent: "",
      shareImage: "",
      shareWithUserInfo: false,
      navigationMode: ["unImmersive"],
      backgroundType: "color",
      backgroundColor: "rgba(245,245,245,1)",
      backgroundImage: "",
      redirect: false,
      redirectURL: "",
      withParams: true,
      customPath: "",
      backgroundColorFill: false,
      backgroundImageColorFill: "rgba(245,245,245,1)",
      forever: false,
      isSeedCRM: false,
      CRMID: "",
      sourceType: "",
      shareWaistbandMode: [],
      backWashMask: false,
      keywords: "",
      pcAdapter: false,
      language: "zh",
      canvasRecs: {
        x: 791.5,
        y: 290,
        width: 306,
        height: 525,
        top: 290,
        right: 1097.5,
        bottom: 815,
        left: 791.5,
      },
      previewContainerRecs: {
        x: 791.5,
        y: 290,
        width: 306,
        height: 525,
        top: 290,
        right: 1097.5,
        bottom: 815,
        left: 791.5,
      },
    },
    mark: "activity-1710828881409",
  },
  awardIdList: [],
  conditionIdList: [],
  dialog: [],
  anchor: [],
  componentIndex: 0,
  activeTab: 0,
  currentMark: "vue-button-1710828895681",
  bottomIndex: 500,
  topIndex: 500,
  fixedHeight: 100,
  grid: false,
  createdTime: "",
  remainsProtocolList: [],
  dialogOrdinal: 0,
  fixBottomIndex: 800,
  fixTopIndex: 800,
  isContainerComponent: false,
  isTabsComponent: false,
  isSlidePageComponent: false,
  isSlideTabComponent: false,
};
var activityId = 36504;
var sceneId = null;
var businessLine = "saf";
var date = "20240319";
var activityType = 1;
</script>
`;

module.exports = getPageDeclarationTemplate;
